## service调用版本
demo:
  service:
    version: 1.0.0
 ##dubbo配置
dubbo:
  application:
    name: dubbo-consumer
  consumer:
    timeout: 600000
  protocol:
    name: dubbo
    port: 20880
  registry:
    address: zookeeper://120.79.189.242:2181
##fastDFS服务器地址
image:
  server:
    url: http://120.79.189.242/

server:
  port: 9091

spring:
  application:
    name: dubbo-consumer
  devtools:
    restart:
      additional-paths: resources/**
      enabled: true
  ##这个数据库连接这要用于分页插件不报错，实际没啥用
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/jtmall?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    username: root
  thymeleaf:
    cache: false
#配置日志
logging:
  #此处存放日志的路径
  path:
    config: classpath:log/logback-spring.xml
  #指定不同目录下的日志的级别
  level:
    com.jtmall.manager: DEBUG

######常用键值的配置
#错误信息值
errorMessage: errorMessage
#物品编号
cNumber: cNumber