demo:
  service:
    manager: 1.0.0

dubbo:
  application:
    name: dubbo-provider
  protocol:
    name: dubbo
    port: 20880
  provider:
    timeout: 600000
  registry:
    address: zookeeper://120.79.189.242:2181
    check: false
  scan:
    base-packages: com.jtmall
#dubbo:
#  application:
#    name: sea-provider-log
#  registry:
#    address: zookeeper://120.79.189.242:2181
#  protocol:
#    name: dubbo
#    port: 20552
#  scan:
#    base-packages: com.jtmall

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.jtmall
  ##打印日志到控制台
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
##分页插件
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

server:
  port: 9090

spring:
  application:
    name: dubbo-provider
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/jtmall?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    username: root
  ## redis配置
  redis:
    # Redis服务器地址
    host: 120.79.189.242
    #host: localhost
    # Redis服务器连接端口
    port: 6379 #默认
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器连接密码（默认为空）
    password:
    # 连接超时时间（毫秒）
    timeout: 10000
    # Lettuce
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 10000
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
      # 关闭超时时间
      shutdown-timeout: 100


